export { default as AboutUs } from './AboutUs';
export { default as Amenities } from './Amenities';
export { default as Contact } from './Contact';
export { default as HomePage } from './HomePage';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Rooms } from './Rooms';
export { default as Cart } from './Cart';
export { default as BookingForm } from './BookingForm';
